---
permalink: audit/lkdm-leaked-object-cleanup.html
sidebar: sidebar
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup
summary: ''
---
= LKDM: Leaked Object Cleanup
:icons: font
:imagesdir: ../media/

[.lead]
This message is generated when a leaked chunk has been cleaned or deleted. A chunk can be part of a replicated object or an erasure-encoded object.

[cols="1a,1a,4a" options="header"]
|===
| Code| Field| Description
a|
CLOC
a|
Chunk location
a|
The file path of the leaked chunk that got deleted.
a|
CTYP
a|
Chunk type
a|
Type of chunk:

`ec: Erasure-coded object chunk` 

`repl: Replicated object chunk`
a|
LTYP
a|
Leak type
a|
The five types of leaks that can be detected:

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`
a|
CTIM
a| 
Chunk create time
a|
Time the leaked chunk was created.
a|
UUID
a|
Universally Unique Identifier
a|
The identifier of the object the chunk belongs to.
a|
CBID
a|
Content Block Identifier
a|
CBID of the object the leaked chunk belongs to.
a|
CSIZ
a|
Content size
a|
The size of the chunk in bytes.
|===
//2024-06-04, SGRIDOC-64
