---
permalink: audit/object-storage-audit-messages.html
sidebar: sidebar

keywords: audit, object storage, object management, object retrieval, node transfer, verification, BROR, CBSE, CBRE, CGRR, EBDL, EBKR, SCMT, SREM
summary: 'You should be familiar with audit messages belonging to the object storage audit category. These are events related to the storage and management of objects within the StorageGRID system. These include object storage and retrievals, grid-node to grid-node transfers, and verifications.'
---
= Object storage audit messages
:icons: font
:imagesdir: ../media/

[.lead]
The audit messages belonging to the object storage audit category are used for events related to the storage and management of objects within the StorageGRID system. These include object storage and retrievals, grid-node to grid-node transfers, and verifications.

NOTE: Audit codes are removed from the product and documentation as features are deprecated. If you encounter an audit code that is not listed here, check the previous versions of this topic for older SG releases. For example, https://docs.netapp.com/us-en/storagegrid-118/audit/object-storage-audit-messages.html[StorageGRID 11.8 object storage audit messages^].

[cols="1a,2a,1a" options="header"]
|===
| Code| Description| See

| BROR
| Bucket Read Only Request: A bucket entered or exited read-only mode.
| link:bror-bucket-read-only-request.html[BROR: Bucket Read Only Request]

| CBSE
| Object Send End: The source entity completed a grid-node to grid-node data transfer operation.
| link:cbse-object-send-end.html[CBSE: Object Send End]

| CBRE
| Object Receive End: The destination entity completed a grid-node to grid-node data transfer operation.
| link:cbre-object-receive-end.html[CBRE: Object Receive End]

| CGRR
| Cross-Grid Replication Request: StorageGRID attempted a cross-grid replication operation to replicate objects between buckets in a grid federation connection. 
| link:cgrr-cross-grid-replication-request.html[CGRR: Cross-Grid Replication Request]

| EBDL
| Empty Bucket Delete: The ILM scanner deleted an object in a bucket that is deleting all objects (performing an empty bucket operation).
| link:ebdl-empty-bucket-delete.html[EBDL: Empty Bucket Delete]

| EBKR
| Empty Bucket Request: A user sent a request to turn empty bucket on or off (that is, to delete bucket objects or to stop deleting objects).
| link:ebkr-empty-bucket-request.html[EBKR: Empty Bucket Request]

| SCMT
| Object Store Commit: A content block was completely stored and verified, and can now be requested.
| link:scmt-object-store-commit.html[SCMT: Object Store Commit Request]

| SREM
| Object Store Remove: A content block was deleted from a grid node, and can no longer be requested directly.
| link:srem-object-store-remove.html[SREM: Object Store Remove]
|===
