---
permalink: upgrade/changes-to-tenant-management-api.html
sidebar: sidebar
keywords: tenant management api, api, api version, swagger, rest api
summary: 'StorageGRID 11.9 uses version 4 of the Tenant Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported.'
---
= Changes to the Tenant Management API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.9 uses version 4 of the Tenant Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported. 

NOTE: You can continue to use deprecated versions of the Tenant Management API with StorageGRID 11.9; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 11.9, you can deactivate the deprecated APIs by using the `PUT /grid/config/management` API.

To learn more, go to link:../tenant/understanding-tenant-management-api.html[Understand the Tenant Management API].

== New API for bucket capacity limit
You can use the `/org/containers/{bucketName}/quota-object-bytes` API with GET/PUT operations to get and set the storage capacity limit for a bucket.

// 2024 JUL 10, SGWS-31727