---
permalink: ubuntu/configuring-docker-storage-volume.html
sidebar: sidebar
keywords: how to configure Docker storage volume
summary: 'Before installing Docker, you might need to format the Docker storage volume and mount it on /var/lib/docker.'
---
= Configure container engine storage volume
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the container engine (Docker or Podman), you might need to format the storage volume and mount it.

NOTE: Support for Docker as the container engine for software-only deployments is deprecated. Docker will be replaced with another container engine in a future release.

.About this task

You can skip these steps if you plan to use local storage for the Docker storage volume and have sufficient space available on the host partition containing `/var/lib`.

.Steps

. Create a file system on the Docker storage volume:
+
----
sudo mkfs.ext4 docker-storage-volume-device
----

. Mount the Docker storage volume:
+
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----

. Add an entry for docker-storage-volume-device to /etc/fstab.
+
This step ensures that the storage volume will remount automatically after host reboots.
