---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html
sidebar: sidebar
keywords: how to download ubuntu or debian installation files
summary: 'You must download the StorageGRID installation archive and extract the required files. Optionally, you can manually verify the files in the installation package.'
---
= Download and extract the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archive and extract the required files. Optionally, you can manually verify the files in the installation package.

.Steps

. Go to the https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads page for StorageGRID^].
. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the checkbox.
+
CAUTION: You must apply any required hotfixes after you install the StorageGRID release. For more information, see the link:../maintain/storagegrid-hotfix-procedure.html[hotfix procedure in the recovery and maintenance instructions]

. Read the End User License Agreement, select the checkbox, and then select *Accept & Continue*.
. In the *Install StorageGRID* column, select the .tgz or .zip installation archive for Ubuntu or Debian.
+
NOTE: Select the `.zip` file if you are running Windows on the service laptop.

. Save the installation archive.

. [[ubuntu-download-verification-package]]If you need to verify the installation archive:
.. Download the StorageGRID code signature verification package. The file name for this package uses the format `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`, where `<version-number>` is the StorageGRID software version.
.. Follow the steps to link:../ubuntu/download-files-verify.html[manually verify the installation files]. 

. Extract the files from the installation archive.
. Choose the files you need.
+
The files you need depends on your planned grid topology and how you will deploy your StorageGRID system.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive.

include::../_include/installation-files-ubuntu.adoc[]