---
permalink: ubuntu/installing-linux.html
sidebar: sidebar
keywords: how to install Linux
summary: 'You must install StorageGRID on all Ubuntu or Debian grid hosts. For a list of supported versions, use the NetApp Interoperability Matrix Tool.'
---
= Install Linux
:icons: font
:imagesdir: ../media/

[.lead]
You must install StorageGRID on all Ubuntu or Debian grid hosts. For a list of supported versions, use the NetApp Interoperability Matrix Tool.

.Before you begin

Ensure your operating system meets StorageGRID's minimum kernel version requirements, as listed below. Use the command `uname -r` to get your operating system's kernel version, or consult with your OS vendor.

*Note:* Support for Ubuntu versions 18.04 and 20.04 have been deprecated and will be removed in a future release.

[cols="1a,2a,3a" options="header"]
|===
| Ubuntu version| Minimum kernel version| Kernel package name

| 18.04.6 (deprecated)
| 5.4.0-150-generic
| linux-image-5.4.0-150-generic/bionic-updates,bionic-security,now 5.4.0-150.167~18.04.1

| 20.04.5 (deprecated)
| 5.4.0-131-generic
| linux-image-5.4.0-131-generic/focal-updates,now 5.4.0-131.147

| 22.04.1
| 5.15.0-47-generic
| linux-image-5.15.0-47-generic/jammy-updates,jammy-security,now 5.15.0-47.51

| 24.04
| 6.8.0-31-generic
| linux-image-6.8.0-31-generic/noble,now 6.8.0-31.31
|===

*Note:* Support for Debian version 11 has been deprecated and will be removed in a future release.

[cols="1a,2a,2a" options="header"]
|===
| Debian version| Minimum kernel version| Kernel package name

| 11 (deprecated)
| 5.10.0-18-amd64
| linux-image-5.10.0-18-amd64/stable,now 5.10.150-1

| 12
| 6.1.0-9-amd64
| linux-image-6.1.0-9-amd64/stable,now 6.1.27-1
|===

.Steps

. Install Linux on all physical or virtual grid hosts according to the distributor's instructions or your standard procedure.
+
NOTE: Don't install any graphical desktop environments. When installing Ubuntu, you must select *standard system utilities*. Selecting *OpenSSH server* is recommended to enable ssh access to your Ubuntu hosts. All other options can remain cleared.

. Ensure that all hosts have access to Ubuntu or Debian package repositories.
. If swap is enabled:
 .. Run the following command: `$ sudo swapoff --all`
 .. Remove all swap entries from `/etc/fstab` to persist the settings.
+

NOTE: Failing to disable swap entirely can severely lower performance.