---
permalink: harden/index.html
sidebar: sidebar
keywords: Hardening guidelines, system, security
summary: 'System hardening is the process of eliminating as many security risks as possible from a StorageGRID system.'
---
= General considerations for system hardening
:icons: font
:imagesdir: ../media/

[.lead]
System hardening is the process of eliminating as many security risks as possible from a StorageGRID system.

As you install and configure StorageGRID, use these guidelines to help you meet any prescribed security objectives for confidentiality, integrity, and availability.

You should already be using industry-standard best practices for system hardening. For example, you use strong passwords for StorageGRID, use HTTPS instead of HTTP, and enable certificate-based authentication where available.

StorageGRID follows the https://security.netapp.com/policy/[NetApp Vulnerability Handling Policy^]. Reported vulnerabilities are verified and addressed according to the product security incident response process.

When hardening a StorageGRID system, consider the following:

* *Which of the three StorageGRID networks* you have implemented. All StorageGRID systems must use the Grid Network, but you might also be using the Admin Network, the Client Network, or both. Each network has different security considerations.
* *The type of platforms* you use for the individual nodes in your StorageGRID system. StorageGRID nodes can be deployed on VMware virtual machines, within a container engine on Linux hosts, or as dedicated hardware appliances. Each type of platform has its own set of hardening best practices.
* *How trusted the tenant accounts are*. If you are a service provider with untrusted tenant accounts, you will have different security concerns than if you only use trusted, in-house tenants.
* *Which security requirements and conventions* your organization follows. You might need to comply with specific regulatory or corporate requirements.