---
permalink: tenant/creating-s3-bucket.html
sidebar: sidebar
keywords: how to create S3 bucket
summary: 'You can use the Tenant Manager to create S3 buckets for object data.'
---
= Create an S3 bucket
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Tenant Manager to create S3 buckets for object data.

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the Root access or Manage all buckets link:tenant-management-permissions.html[permission]. These permissions override the permissions settings in group or bucket policies. 
+
NOTE: Permissions to set or modify S3 Object Lock properties of buckets or objects can be granted by link:../s3/bucket-and-group-access-policies.html[bucket policy or group policy].

* If you plan to enable S3 Object Lock for a bucket, a grid admin has enabled the global S3 Object Lock setting for the StorageGRID system, and you have reviewed the requirements for S3 Object Lock buckets and objects.

* If each tenant will have 5,000 buckets, each Storage Node in the grid has a minimum of 64 GB of RAM.
+
NOTE: Each grid can have a maximum of 100,000 buckets.

== Access the wizard

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.

. Select *Create bucket*.

== Enter details

.Steps

. Enter details for the bucket.
+
[cols="1a,3a" options="header"]
|===

| Field | Description

| Bucket name

| A name for the bucket that complies with these rules:

* Must be unique across each StorageGRID system (not just unique within the tenant account).
* Must be DNS compliant.
* Must contain at least 3 and no more than 63 characters.
* Each label must start and end with a lowercase letter or a number and can only use lowercase letters, numbers, and hyphens.
* Must not contain periods in virtual hosted style requests. Periods will cause problems with server wildcard certificate verification.

For more information, see the https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html[Amazon Web Services (AWS) documentation on bucket naming rules^].

*Note*: You can't change the bucket name after creating the bucket.

| Region 

| The bucket's region.

Your StorageGRID administrator manages the available regions. A bucket's region can affect the data-protection policy applied to objects. By default, all buckets are created in the `us-east-1` region.

*Note*: You can't change the region after creating the bucket.

|===
. Select *Continue*.

== Manage settings

.Steps

. Optionally, enable object versioning for the bucket.
+
Enable object versioning if you want to store every version of each object in this bucket. You can then retrieve previous versions of an object as needed. You must enable object versioning if the bucket will be used for cross-grid replication.

. If the global S3 Object Lock setting is enabled, optionally enable S3 Object Lock for the bucket to store objects using a write-once-read-many (WORM) model. 
+
Enable S3 Object Lock for a bucket only if you need to keep objects for fixed amount of time, for example, to meet certain regulatory requirements. S3 Object Lock is a permanent setting that helps you prevent objects from being deleted or overwritten for a fixed amount of time or indefinitely. 
+
CAUTION: After the S3 Object Lock setting is enabled for a bucket, it can't be disabled. Anyone with the correct permissions can add objects to this bucket that can't be changed. You might not be able to delete these objects or the bucket itself.
+
If you enable S3 Object Lock for a bucket, bucket versioning is enabled automatically.

. If you selected *Enable S3 Object Lock*, optionally enable *Default retention* for this bucket.
+
NOTE: Your grid administrator must give you permission to link:../tenant/using-s3-object-lock.html[use specific features of S3 Object Lock].
+
When *Default retention* is enabled, new objects added to the bucket will be automatically protected from being deleted or overwritten. The *Default retention* setting does not apply to objects that have their own retention periods.

.. If *Default retention* is enabled, specify a *Default retention mode* for the bucket.
+
include::../_include/bucket-governance-compliance.adoc[]

.. If *Default retention* is enabled, specify the *Default retention period* for the bucket.
+
The *Default retention period* indicates how long new objects added to this bucket should be retained, starting from the time they are ingested. Specify a value that is less than or equal to the maximum retention period for the tenant, as set by the grid administrator.
+
A _maximum_ retention period, which can be a value from 1 day to 100 years, is set when the grid administrator creates the tenant. When you set a _default_ retention period, it can't exceed the value set for the maximum retention period. If needed, ask your grid administrator to increase or decrease the maximum retention period.

. [[capacity-limit]]Optionally, select *Enable capacity limit*.
+
Capacity limit is the maximum capacity available for this bucket's objects. This value represents a logical amount (object size), not a physical amount (size on disk).
+
If no limit is set, the capacity for this bucket is unlimited. Refer to link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage[Capacity limit usage] for more information.

. Select *Create bucket*.
+
The bucket is created and added to the table on the Buckets page.

. Optionally, select *Go to bucket details page* to link:viewing-s3-bucket-details.html[view bucket details] and perform additional configuration.