---
permalink: tenant/ilm-policy-tags.html
sidebar: sidebar
keywords: how to assign ilm policy tag to bucket
summary: 'Choose an ILM policy tag to assign to a bucket based on your object storage requirements.'
---
= Apply an ILM policy tag to a bucket
:icons: font
:imagesdir: ../media/

[.lead]
Choose an ILM policy tag to apply to a bucket based on your object storage requirements.

The ILM policy controls where the object data is stored and whether it is deleted after a certain time period. Your grid administrator creates ILM policies and assigns them to ILM policy tags when using multiple active policies.

NOTE: Avoid frequently reassigning a bucket's policy tag. Otherwise, performance issues might occur.

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Root access, Manage all buckets, or View all buckets permission]. These permissions override the permission settings in group or bucket policies.

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears. As required, you can sort the information by any column, or you can page forward and back through the list.

. Select the name of the bucket you want to assign an ILM policy tag to.
+
You can also change the ILM policy tag assignment for a bucket that already has a tag assigned.
+
NOTE: The Object Count and Space Used values displayed are estimates. These estimates are affected by the timing of ingests, network connectivity, and node status. If buckets have versioning enabled, deleted object versions are included in the object count.

. In the Bucket options tab, expand the ILM policy tag accordion. This accordion only appears if your grid administrator has enabled the use of custom policy tags.

. Read the description of each policy tag to determine which tag should be applied to the bucket.
+
CAUTION: Changing the ILM policy tag for a bucket will trigger ILM reevaluation of all objects in the bucket. If the new policy retains objects for a limited time, older objects will be deleted.

. Select the radio button for the tag you want to assign to the bucket.

. Select *Save changes*. A new S3 bucket tag will be set on the bucket with the key `NTAP-SG-ILM-BUCKET-TAG` and the value of the ILM policy tag name.
+
CAUTION: Ensure that your S3 applications do not accidentally override or delete the new bucket tag. If this tag is omitted when applying a new TagSet to the bucket, objects in the bucket will revert to being evaluated against the default ILM policy.
+
CAUTION: Set and modify ILM policy tags using only the Tenant Manager or Tenant Manager API where the ILM policy tag is validated. Do not modify the `NTAP-SG-ILM-BUCKET-TAG` ILM policy tag using the S3 PutBucketTagging API or the S3 DeleteBucketTagging API.
+
NOTE: Changing the policy tag assigned to a bucket has a temporary performance impact while objects are being reevaluated using the new ILM policy.

// 2023 NOV 21, SGRIDDOC-25