---
permalink: tenant/manage-bucket-consistency.html
sidebar: sidebar
keywords: how to manage bucket consistency, how to change bucket consistency, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global
summary: 'Consistency values can be used to specify the availability of bucket setting changes as well as to provide a balance between the availability of the objects within a bucket and the consistency of those objects across different Storage Nodes and sites. You can change the consistency values to be different from the default values so that client applications can meet their operational needs.'
---
= Manage bucket consistency
:icons: font
:imagesdir: ../media/

[.lead]
Consistency values can be used to specify the availability of bucket setting changes as well as to provide a balance between the availability of the objects within a bucket and the consistency of those objects across different Storage Nodes and sites. You can change the consistency values to be different from the default values so that client applications can meet their operational needs.

.Before you begin
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Manage all buckets or Root access permission]. These permissions override the permissions settings in group or bucket policies.

== Bucket consistency guidelines

The bucket consistency is used to determine the consistency for client applications affecting objects within that S3 bucket. In general, you should use the *Read-after-new-write* consistency for your buckets.

== [[change-bucket-consistency]]Change bucket consistency

If the *Read-after-new-write* consistency does not meet the client application's requirements, you can change the consistency by setting the bucket consistency or by using the `Consistency-Control` header. The `Consistency-Control` header overrides the bucket consistency.

NOTE: When you change a bucket's consistency, only those objects that are ingested after the change are guaranteed to meet the revised setting.

.Steps

. Select *View buckets* from the dashboard, or select *STORAGE (S3)* > *Buckets*.
. Select the bucket name from the table.
+
The bucket details page appears.

. From the *Bucket options* tab, select the ** accordion.

. Select a consistency for operations performed on the objects in this bucket.
+
* *All*: Provides the highest level of consistency. All nodes receive the data immediately, or the request will fail.

* *Strong-global*: Guarantees read-after-write consistency for all client requests across all sites.

* *Strong-site*: Guarantees read-after-write consistency for all client requests within a site.

* *Read-after-new-write* (default): Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Recommended for most cases.

* *Available*: Provides eventual consistency for both new objects and object updates. For S3 buckets, use only as required (for example, for a bucket that contains log values that are rarely read, or for HEAD or GET operations on keys that don't exist). Not supported for S3 FabricPool buckets.

. Select *Save changes*.

== What happens when you change bucket settings

Buckets have multiple settings that affect the behavior of the buckets and the objects within those buckets. 

The following bucket settings use *strong* consistency by default. If two or more Storage Nodes are not available within any site, or if a site is not available, any changes to these settings might not be available.

* link:deleting-s3-bucket-objects.html[Background empty bucket deletion]
* link:enabling-or-disabling-last-access-time-updates.html[Last Access Time]
* link:../s3/create-s3-lifecycle-configuration.html[Bucket lifecycle]
* link:../s3/bucket-and-group-access-policies.html[Bucket policy]
* link:../s3/operations-on-buckets.html[Bucket tagging]
* link:changing-bucket-versioning.html[Bucket versioning]
* link:using-s3-object-lock.html[S3 Object Lock]
* link:../admin/reviewing-storagegrid-encryption-methods.html#bucket-encryption-table[Bucket encryption]

NOTE: The consistency value for bucket versioning, S3 Object Lock, and bucket encryption cannot be set to a value that is not strongly consistent.

The following bucket settings do not use strong consistency and have higher availability for changes. Changes to these settings might take some time before having an effect.

* link:considerations-for-platform-services.html[Platform services configuration: Notification, Replication, or Search integration]
* link:configuring-cross-origin-resource-sharing-cors.html[CORS configuration]
* <<change-bucket-consistency,Change bucket consistency>>

TIP: If the default consistency used when changing bucket settings does not meet the client application's requirements, you can change the consistency by using the `Consistency-Control` header for the link:../s3/put-bucket-consistency-request.html[S3 REST API] or by using the `reducedConsistency` or `force` options in the link:understanding-tenant-management-api.html[Tenant Management API].