---
permalink: tenant/manage-bucket-policy.html
sidebar: sidebar
keywords: how to create S3 tenant groups, federated group, local group
summary: 'You can control user access for an S3 bucket and the objects in that bucket.'
---
= Manage bucket policy
:icons: font
:imagesdir: ../media/

[.lead]
You can control user access for an S3 bucket and the objects in that bucket.

.Before you begin
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Root access permission]. The View all buckets and Manage all buckets permissions only allow viewing.
* You've verified that the required number of Storage Nodes and sites are available. If two or more Storage Nodes are not available within any site, or if a site is not available, changes to these settings might not be available.

.Steps

. Select *Buckets*, then select the bucket you want to manage.

. On the bucket details page, select *Bucket access* > *Bucket policy*.

. Do one of the following:
+
* Enter a bucket policy by selecting the *Enable policy* checkbox. Then enter a valid JSON formatted string.
+
Each bucket policy has a size limit of 20,480 bytes.
* Modify an existing policy by editing the string.
* Disable a policy by unselecting *Enable policy*.

For detailed information about bucket policies, including language syntax and examples, see link:../s3/example-bucket-policies.html[Example bucket policies].