---
permalink: tenant/understanding-notifications-for-buckets.html
sidebar: sidebar
keywords: s3 bucket event notification, sequencer key
summary: 'You can enable event notification for an S3 bucket if you want StorageGRID to send notifications about specified events to a destination Kafka cluster or Amazon Simple Notification Service.'
---
= Understand notifications for buckets
:icons: font
:imagesdir: ../media/

[.lead]
You can enable event notification for an S3 bucket if you want StorageGRID to send notifications about specified events to a destination Kafka cluster or Amazon Simple Notification Service.

For example, you could configure alerts to be sent to administrators about each object added to a bucket, where the objects represent log files associated with a critical system event.

Event notifications are created at the source bucket as specified in the notification configuration and are delivered to the destination. If an event associated with an object succeeds, a notification about that event is created and queued for delivery.

The uniqueness and ordering of notifications aren't guaranteed. More than one notification of an event might be delivered to the destination as a result of operations taken to guarantee delivery success. And because delivery is asynchronous, the time ordering of notifications at the destination is not guaranteed to match the ordering of events on the source bucket, particularly for operations that originate from different StorageGRID sites. You can use the `sequencer` key in the event message to determine the order of events for a particular object, as described in Amazon S3 documentation.

StorageGRID event notifications follow the Amazon S3 API with some limitations.

* The following event types are supported:

** s3:ObjectCreated:
** s3:ObjectCreated:Put
** s3:ObjectCreated:Post
** s3:ObjectCreated:Copy
** s3:ObjectCreated:CompleteMultipartUpload
** s3:ObjectRemoved:
** s3:ObjectRemoved:Delete
** s3:ObjectRemoved:DeleteMarkerCreated
** s3:ObjectRestore:Post

* Event notifications sent from StorageGRID use the standard JSON format but don't include some keys and use specific values for others, as shown in the table:

[cols="1a,2a" options="header"]
|===
| Key name| StorageGRID value
| eventSource
| `sgws:s3`

| awsRegion
| _not included_

| x-amz-id-2
| _not included_

| arn
| `urn:sgws:s3:::bucket_name`
|===