---
permalink: tenant/update-default-retention-settings.html
sidebar: sidebar
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance
summary: 'If you enabled S3 Object Lock when you created the bucket, you can edit the bucket to change the default retention settings. You can enable (or disable) default retention and set a default retention mode and retention period.'
---
= Update S3 Object Lock default retention
:icons: font
:imagesdir: ../media/

[.lead]
If you enabled S3 Object Lock when you created the bucket, you can edit the bucket to change the default retention settings. You can enable (or disable) default retention and set a default retention mode and retention period.

.Before you begin
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Manage all buckets or Root access permission]. These permissions override the permissions settings in group or bucket policies.

* S3 Object Lock is enabled globally for your StorageGRID system, and you enabled S3 Object Lock when you created the bucket. See link:using-s3-object-lock.html[Use S3 Object Lock to retain objects].

.Steps
. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.

. Select the bucket name from the table.
+
The bucket details page appears.

. From the *Bucket options* tab, select the *S3 Object Lock* accordion.

. Optionally, enable or disable *Default retention* for this bucket.
+
Changes to this setting don't apply to objects already in the bucket or to any objects that might have their own retention periods.

. If *Default retention* is enabled, specify a *Default retention mode* for the bucket.
+
include::../_include/bucket-governance-compliance.adoc[]

. If *Default retention* is enabled, specify the *Default retention period* for the bucket.
+
The *Default retention period* indicates how long new objects added to this bucket should be retained, starting from the time they are ingested. Specify a value that is less than or equal to the maximum retention period for the tenant, as set by the grid administrator.
+
A _maximum_ retention period, which can be a value from 1 day to 100 years, is set when the grid administrator creates the tenant. When you set a _default_ retention period, it can't exceed the value set for the maximum retention period. If needed, ask your grid administrator to increase or decrease the maximum retention period.

. Select *Save changes*.