---
permalink: tenant/use-s3-console.html
sidebar: sidebar
keywords: how to use s3 console
summary: 'You can use S3 Console to view and manage the objects in an S3 bucket.'
---
= Use S3 Console
:icons: font
:imagesdir: ../media/

[.lead]
You can use S3 Console to view and manage the objects in an S3 bucket.

S3 Console allows you to:

* Upload, download, rename, copy, move, and delete objects
* View, revert, download, and delete object versions
* Search for objects by prefix
* Manage object tags
* View object metadata
* View, create, rename, copy, move, and delete folders

[NOTE]
====
S3 Console provides an improved user experience for the most common cases. It is not designed to replace CLI or API operations in all situations.
 
If using S3 Console results in operations taking too long (for example, minutes or hours), consider:

* Reducing the number of selected objects
* Using non-graphical (API or CLI) methods to access your data
====

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* If you want to manage objects, you belong to a user group that has the Root access permission. Alternatively, you belong to a user group that has the Use S3 Console tab permission and either the View all buckets permission or Manage all buckets permission. See link:tenant-management-permissions.html[Tenant management permissions].
* An S3 Group or Bucket policy has been configured for the user. See link:../s3/bucket-and-group-access-policies.html[Use bucket and group access policies].
* You know the user's access key ID and secret access key. Optionally, you have a `.csv` file containing this information. See the link:creating-your-own-s3-access-keys.html[instructions for creating access keys].

.Steps

. Select *STORAGE* > *Buckets* > *_bucket name_*.
. Select the S3 Console tab.
. Paste the access key ID and secret access key into the fields. Otherwise, select *Upload access keys* and select your `.csv` file.
. Select *Sign in*.
. The table of bucket objects appears. You can manage objects as needed. 

.Additional information

* *Search by prefix*: The prefix search feature only searches for objects that begin with a specific word relative to the current folder. The search does not include objects that contain the word elsewhere. This rule also applies to objects within folders. For example, a search for `folder1/folder2/somefile-` would return objects that are within the `folder1/folder2/` folder and begin with the word `somefile-`.

* *Drag and drop*: You can drag and drop files from your computer's file manager to S3 Console. However, you cannot upload folders.

* *Operations on folders*: When you move, copy, or rename a folder, all objects in the folder are updated one at a time, which might take time.

* *Permanent deletion when bucket versioning is disabled*: When you overwrite or delete an object in a bucket with versioning disabled, the operation is permanent. See link:changing-bucket-versioning.html[Change object versioning for a bucket].

// 2023 AUG 23, SGWS-27720 and SGWS-27719 
