---
permalink: tenant/viewing-s3-bucket-details.html
sidebar: sidebar
keywords: how to view bucket details
summary: 'You can view the buckets in your tenant account.'
---
= View bucket details
:icons: font
:imagesdir: ../media/

[.lead]
You can view the buckets in your tenant account.

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the link:tenant-management-permissions.html[Root access, Manage all buckets, or View all buckets permission]. These permissions override the permission settings in group or bucket policies.

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears.

. Review the summary table for each bucket.
+
As required, you can sort the information by any column, or you can page forward and back through the list.
+
NOTE: The Object Count, Space Used, and Usage values displayed are estimates. These estimates are affected by the timing of ingests, network connectivity, and node status. If buckets have versioning enabled, deleted object versions are included in the object count.
+
Name:: The bucket's unique name, which can't be changed.

Enabled features:: The list of features that are enabled for the bucket.

S3 Object Lock:: Whether S3 Object Lock is enabled for the bucket.
+
This column appears only if S3 Object Lock is enabled for the grid. This column also shows information for any legacy Compliant buckets.

Region:: The bucket's region, which can't be changed. This column is hidden by default.

Object count:: The number of objects in this bucket. If buckets have versioning enabled, non-current object versions are included in this value.
+
When objects are added or deleted, this value might not update immediately. 

Space used:: The logical size of all objects in the bucket. The logical size does not include the actual space required for replicated or erasure-coded copies or for object metadata.
+
This value can take up to 10 minutes to update.

Usage:: The percentage used of the bucket's capacity limit, if one has been set.
+
The usage value is based on internal estimates and might be exceeded in some cases. For example, StorageGRID checks capacity limit (if set) when a tenant starts uploading objects and rejects new ingests to this bucket if the tenant has exceeded the capacity limit. However, StorageGRID does not take into account the size of the current upload when determining if the capacity limit has been exceeded. If objects are deleted, a tenant might be temporarily prevented from uploading new objects to this bucket until the capacity limit usage is recalculated. The calculations can take 10 minutes or longer.
+
This value indicates logical size, not physical size needed to store the objects and their metadata.

Capacity:: If set, the capacity limit for the bucket.

Date created:: The date and time the bucket was created. This column is hidden by default.

. To view details for a specific bucket, select the bucket name from the table.

.. View the summary information at the top of the web page to confirm the details for the bucket, such as Region and Object count.

.. View the Capacity limit usage bar. If the usage is 100% or near 100%, consider increasing the limit or deleting some objects.

.. As needed, select *Delete objects in bucket* and *Delete bucket*.
+
[CAUTION]
====
Pay close attention to the cautions that appear when you select each of these options. For more information, refer to:

* link:deleting-s3-bucket-objects.html[Delete all objects in a bucket]

* link:deleting-s3-bucket.html[Delete a bucket] (bucket must be empty)
====

.. View or change settings for the bucket in each of the tabs as needed.
+
* *S3 Console*: View the objects for the bucket. For more information, refer to link:use-s3-console.html[Use S3 Console].

* *Bucket options*: View or change option settings. Some settings, such as S3 Object Lock, can't be changed after the bucket is created.
** link:manage-bucket-consistency.html[Manage bucket consistency]
** link:enabling-or-disabling-last-access-time-updates.html[Last access time updates]
** link:../tenant/creating-s3-bucket.html#capacity-limit[Capacity limit]
** link:changing-bucket-versioning.html[Object versioning]
** link:using-s3-object-lock.html[S3 Object Lock]
** link:update-default-retention-settings.html[Default bucket retention]
** link:grid-federation-manage-cross-grid-replication.html[Manage cross-grid replication] (if allowed for the tenant)
* *Platform services*: link:considerations-for-platform-services.html[Manage platform services] (if allowed for the tenant)

* *Bucket access*: View or change option settings. You must have specific access permissions.
** Configure link:configuring-cross-origin-resource-sharing-cors.html[Cross-Origin Resource Sharing (CORS)] so the bucket and objects in the bucket will be accessible to web applications in other domains.
** link:../tenant/manage-bucket-policy.html[Control user access] for an S3 bucket and objects in that bucket.