---
permalink: vmware/software-requirements.html
sidebar: sidebar
keywords: software requirements
summary: 'You can use a virtual machine to host any type of StorageGRID node. You need one virtual machine for each grid node.'
---
= Software requirements for VMware
:icons: font
:imagesdir: ../media/

[.lead]
You can use a virtual machine to host any type of StorageGRID node. You need one virtual machine for each grid node.

== VMware vSphere Hypervisor

You must install VMware vSphere Hypervisor on a prepared physical server. The hardware must be configured correctly (including firmware versions and BIOS settings) before you install VMware software.

* Configure networking in the hypervisor as required to support networking for the StorageGRID system you are installing.
+
link:../network/index.html[Networking guidelines]

* Ensure that the datastore is large enough for the virtual machines and virtual disks that are required to host the grid nodes.
* If you create more than one datastore, name each datastore so that you can easily identify which datastore to use for each grid node when you create virtual machines.

== ESX host configuration requirements

CAUTION: You must properly configure the network time protocol (NTP) on each ESX host. If the host time is incorrect, negative effects, including data loss, could occur.

== VMware configuration requirements

You must install and configure VMware vSphere and vCenter before deploying StorageGRID nodes.

For supported versions of VMware vSphere Hypervisor and VMware vCenter Server software, see the https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix Tool^].

For the steps required to install these VMware products, see the VMware documentation.
