---
permalink: rhel/installing-linux.html
sidebar: sidebar
keywords: how to install on red hat linux
summary: 'You must install StorageGRID on all Red Hat Enterprise Linux grid hosts. For a list of supported versions, use the NetApp Interoperability Matrix Tool.'
---
= Install Linux
:icons: font
:imagesdir: ../media/

[.lead]
You must install StorageGRID on all Red Hat Enterprise Linux grid hosts. For a list of supported versions, use the NetApp Interoperability Matrix Tool.

.Before you begin

Ensure your operating system meets StorageGRID's minimum kernel version requirements, as listed below. Use the command `uname -r` to get your operating system's kernel version, or consult with your OS vendor.

[cols="1a,2a,2a" options="header"]
|===
| Red Hat Enterprise Linux version| Minimum kernel version| Kernel package name

| 8.8 (deprecated)
| 4.18.0-477.10.1.el8_8.x86_64
| kernel-4.18.0-477.10.1.el8_8.x86_64

| 8.10
| 4.18.0-553.el8_10.x86_64
| kernel-4.18.0-553.el8_10.x86_64

| 9.0 (deprecated)
| 5.14.0-70.22.1.el9_0.x86_64
| kernel-5.14.0-70.22.1.el9_0.x86_64

| 9.2 (deprecated)
| 5.14.0-284.11.1.el9_2.x86_64
| kernel-5.14.0-284.11.1.el9_2.x86_64

| 9.4
| 5.14.0-427.18.1.el9_4.x86_64
| kernel-5.14.0-427.18.1.el9_4.x86_64

| 9.6
| 5.14.0-570.18.1.el9_6.x86_64
| kernel-5.14.0-570.18.1.el9_6.x86_64
|===

.Steps

. Install Linux on all physical or virtual grid hosts according to the distributor's instructions or your standard procedure.
+
NOTE: If you are using the standard Linux installer, select the "compute node" software configuration, if available, or "minimal install" base environment. Don't install any graphical desktop environments.

. Ensure that all hosts have access to package repositories, including the Extras channel.
+
You might need these additional packages later in this installation procedure.

. If swap is enabled:
 .. Run the following command: `$ sudo swapoff --all`
 .. Remove all swap entries from `/etc/fstab` to persist the settings.

+
NOTE: Failing to disable swap entirely can severely lower performance.