---
permalink: rhel/required-materials.html
sidebar: sidebar
keywords: installation materials red hat linux
summary: 'Before you install StorageGRID, gather and prepare the required materials.'
---
= Required information and materials
:icons: font
:imagesdir: ../media/

[.lead]
Before you install StorageGRID, gather and prepare the required information and materials.

== Required information

Network plan:: Which networks you intend to attach to each StorageGRID node. StorageGRID supports multiple networks for traffic separation, security, and administrative convenience.
+
See the StorageGRID link:../network/index.html[Networking guidelines].

Network information:: IP addresses to assign to each grid node and the IP addresses of the DNS and NTP servers.

Servers for grid nodes:: Identify a set of servers (physical, virtual, or both) that, in aggregate, provide sufficient resources to support the number and type of StorageGRID nodes you plan to deploy.
+
NOTE: If your StorageGRID installation will not use StorageGRID appliance (hardware) Storage Nodes, you must use hardware RAID storage with battery-backed write cache (BBWC). StorageGRID does not support the use of virtual storage area networks (vSANs), software RAID, or no RAID protection.

Node migration (if needed):: Understand the link:node-container-migration-requirements.html[requirements for node migration], if you want to perform scheduled maintenance on physical hosts without any service interruption.

Related information:: https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix Tool^]

== Required materials

NetApp StorageGRID license:: You must have a valid, digitally signed NetApp license.

NOTE: A non-production license, which can be used for testing and proof of concept grids, is included in the StorageGRID installation archive.

StorageGRID installation archive:: link:downloading-and-extracting-storagegrid-installation-files.html[Download the StorageGRID installation archive and extract the files].

Service laptop:: The StorageGRID system is installed through a service laptop.
+
The service laptop must have:

* Network port
* SSH client (for example, PuTTY)
* link:../admin/web-browser-requirements.html[Supported web browser]

StorageGRID documentation:: 
* link:../release-notes/index.html[Release notes]
* link:../admin/index.html[Instructions for administering StorageGRID]