---
permalink: admin/change-ssh-access-passwords.html
sidebar: sidebar
keywords: ssh access keys, change ssh access keys
summary: 'Changing the SSH access passwords for Admin Nodes also updates the unique sets of internal SSH keys for each node in the grid. The primary Admin Node uses these SSH keys to access nodes using secure, passwordless authentication.'
---
= Change SSH access passwords for Admin Nodes
:icons: font
:imagesdir: ../media/

[.lead]
Changing the SSH access passwords for Admin Nodes also updates the unique sets of internal SSH keys for each node in the grid. The primary Admin Node uses these SSH keys to access nodes using secure, passwordless authentication.

Use an SSH key to log in to a node as `admin` or to the root user on a VM or physical console connection.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:admin-group-permissions.html[Maintenance or Root access permission].
* You have the current provisioning passphrase.

.About this task

The new access passwords for Admin Nodes and the new internal keys for each node are stored in the `Passwords.txt` file in the Recovery Package. The keys are listed in the Password column in that file.

There are separate SSH access passwords for the SSH keys used for communication between nodes. Those aren't changed by this procedure.

== Access the wizard

.Steps
. Select *CONFIGURATION* > *Access control* > *Grid passwords*.

. Under *Change SSH keys*, select *Make a change*.

== [[download-current]]Download the current recovery package

Before changing SSH access keys, download the current Recovery Package. You can use the keys in this file if the key change process fails for any node.

.Steps

. Enter the provisioning passphrase for your grid.

. Select *Download recovery package*.

. Copy the Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select *Continue*.

. When the confirmation dialog appears, select *Yes* if you are ready to start changing the SSH access keys.
+
CAUTION: You can't cancel this process after it starts.

== Change SSH access keys

When the change SSH access keys process starts, a new Recovery Package is generated that includes the new keys. Then, the keys are updated on each node.

.Steps

. Wait for the new Recovery Package to be generated, which might take a few minutes.

. When the Download new Recovery Package button is enabled, select *Download new Recovery Package* and save the new Recovery Package file (`.zip`) to two safe, secure, and separate locations.

. When the download completes:
.. Open the `.zip` file.
.. Confirm that you can access the contents, including the `Passwords.txt` file, which contains the new SSH access keys.
.. Copy the new Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: Don't overwrite the old Recovery Package.
+
The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Wait for the keys to update on each node, which might take a few minutes.
+
If keys are changed for all nodes, a green success banner appears.
+
If there is an error during the update process, a banner message lists the number of nodes that failed to have their keys changed. The system will automatically retry the process on any node that failed to have its key changed. If the process ends with some nodes still not having a changed key, the *Retry* button appears.
+
If the key update failed for one or more nodes: 

.. Review the error messages listed in the table.
.. Resolve the issues.
.. Select *Retry*.
+
Retrying only changes the SSH access keys on the nodes that failed during previous key change attempts. 

. After SSH access keys have been changed for all nodes, delete the <<download-current,first Recovery Package you downloaded>>.

. Optionally, select *MAINTENANCE* > *System* > *Recovery package* to download an additional copy of the new Recovery Package.