---
permalink: admin/configuring-admin-proxy-settings.html
sidebar: sidebar
keywords: admin proxy, autosupport, non-transparent proxy
summary: 'If you send AutoSupport packages using HTTP or HTTPS, you can configure a non-transparent proxy server between Admin Nodes and technical support \(AutoSupport\).'
---
= Configure admin proxy settings
:icons: font
:imagesdir: ../media/

[.lead]
If you send AutoSupport packages using HTTP or HTTPS, you can configure a non-transparent proxy server between Admin Nodes and technical support (AutoSupport).

For more information about AutoSupport, see link:configure-autosupport-grid-manager.html[Configure AutoSupport].

.Before you begin

* You have link:admin-group-permissions.html[specific access permissions].
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].

.About this task

You can configure the settings for a single admin proxy.

.Steps

. Select *CONFIGURATION* > *Security* > *Proxy settings*.
+
The Proxy Settings page appears. By default, Storage is selected in the tab menu.

. Select the *Admin* tab.
. Select the *Enable Admin Proxy* checkbox.
. Enter the hostname or IP address of the proxy server.
. Enter the port used to connect to the proxy server.
. Optionally, enter a username and password for the proxy server.
+
Leave these fields blank if your proxy server does not require a username or a password.

. Select one of the following:
+
* If you want to secure the connection to the admin proxy, select *Verify proxy certificate*. Upload a CA bundle to verify the authenticity of SSL certificates presented by the admin proxy server.
+
CAUTION: AutoSupport on Demand, E-Series AutoSupport through StorageGRID, and Update Path determination on the StorageGRID Upgrade page will not work if a proxy certificate is verified.
+
After you upload the CA bundle, its metadata appears.
+
* If you don't want to validate certificates when communicating with the admin proxy server, select *Do not verify proxy certificate*.

. Select *Save*.
+
After the admin proxy is saved, the proxy server between Admin Nodes and technical support is configured.
+
NOTE: Proxy changes can take up to 10 minutes to take effect.

. If you need to disable the admin proxy, clear the *Enable Admin Proxy* checkbox, and then select *Save*.