---
permalink: admin/configuring-storage-proxy-settings.html
sidebar: sidebar
keywords: storage proxy, non-transparent proxy, platform service endpoint
summary: 'If you are using platform services or Cloud Storage Pools, you can configure a non-transparent proxy between Storage Nodes and the external S3 endpoints. For example, you might need a non-transparent proxy to allow platform services messages to be sent to external endpoints, such as an endpoint on the internet.'
---
= Configure storage proxy
:icons: font
:imagesdir: ../media/

[.lead]
If you are using platform services or Cloud Storage Pools, you can configure a non-transparent proxy between Storage Nodes and the external S3 endpoints. For example, you might need a non-transparent proxy to allow platform services messages to be sent to external endpoints, such as an endpoint on the internet. 

NOTE: Configured storage proxy settings do not apply to Kafka platform services endpoints.

.Before you begin

* You have link:admin-group-permissions.html[specific access permissions].
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].

.About this task

You can configure the settings for a single storage proxy.

.Steps

. Select *CONFIGURATION* > *Security* > *Proxy settings*.


. On the *Storage* tab, select the *Enable storage proxy* checkbox.

. Select the protocol for the storage proxy.
. Enter the hostname or IP address of the proxy server.
. Optionally, enter the port used to connect to the proxy server.
+
Leave this field blank to use the default port for the protocol: 80 for HTTP or 1080 for SOCKS5.

. Select *Save*.
+
After the storage proxy is saved, new endpoints for platform services or Cloud Storage Pools can be configured and tested.
+
NOTE: Proxy changes can take up to 10 minutes to take effect.

. Check the settings of your proxy server to ensure that platform service-related messages from StorageGRID will not be blocked.

. If you need to disable a storage proxy, clear the checkbox, and select *Save*.

// 2023 SEP 15, SGWS-25330