---
permalink: s3/changes-to-s3-rest-api-support.html
sidebar: sidebar
keywords: s3 rest api support changes
summary: 'You should be aware of changes to the StorageGRID system’s support for the S3 REST API.'
---
= Changes to S3 REST API support
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of changes to the StorageGRID system's support for the S3 REST API.

[cols="1a,4a" options="header"]
|===
| Release| Comments

|11.8
|
* Added support for `ExpiredObjectDeleteMarker` in a PutBucketLifecycleConfiguration operation, which deletes expired object delete markers.
* Added support for the `s3:ExistingObjectTag/<tag-key>` policy condition key, which requires that existing objects have the specific tag key and value.
* Added support for the `s3:RequestObjectTag/<tag-key>` policy condition key, which requires a specific tag and key value when the object request includes tagging.

|11.7
|
* Added support for using GOVERNANCE mode with S3 Object Lock.
* Added support for the StorageGRID-specific `x-ntap-sg-cgr-replication-status` response header for GetObject and HeadObject requests. This header provides an object's replication status for cross-grid replication.
* SelectObjectContent requests now support Parquet objects.

|11.6
|
* Added support for using the `partNumber` request parameter in GetObject and HeadObject requests.
* Added support for a default retention mode and a default retention period at the bucket level for S3 Object Lock.
* Added support for the `s3:object-lock-remaining-retention-days` policy condition key to set the range of allowable retention periods for your objects.
* Changed the maximum _recommended_ size for a single PutObject operation to 5 GiB (5,368,709,120 bytes). If you have objects that are larger than 5 GiB, use multipart upload instead. 

|11.5
|
* Added support for managing bucket encryption.
* Added support for S3 Object Lock and deprecated legacy Compliance requests.
* Added support for using DeleteObjects on versioned buckets.
* The `Content-MD5` request header is now correctly supported.

|11.4
|
* Added support for DeleteBucketTagging, GetBucketTagging, and PutBucketTagging. Cost allocation tags aren't supported.
* For buckets created in StorageGRID 11.4, restricting object key names to meet performance best practices is no longer required.
* Added support for bucket notifications on the `s3:ObjectRestore:Post` event type.
* AWS size limits for multipart parts are now enforced. Each part in a multipart upload must be between 5 MiB and 5 GiB. The last part can be smaller than 5 MiB.
* Added support for TLS 1.3

|11.3
|

* Added support for server-side encryption of object data with customer-provided keys (SSE-C).
* Added support for DeleteBucketLifecycle, GetBucketLifecycleConfiguration, and PutBucketLifecycleConfiguration operations (Expiration action only) and for the `x-amz-expiration` response header.
* Updated PutObject, CopyObject, and MultipartUpload to describe the impact of ILM rules that use synchronous placement at ingest.
* TLS 1.1 ciphers are no longer supported.

|11.2
|Added support for RestoreObject for use with Cloud Storage Pools. Added support for using the AWS syntax for ARN, policy condition keys, and policy variables in group and bucket policies. Existing group and bucket policies that use the StorageGRID syntax will continue to be supported.

*Note:* Uses of ARN/URN in other configuration JSON/XML, including those used in custom StorageGRID features, have not changed.

|11.1
|Added support for cross-origin resource sharing (CORS), HTTP for S3 client connections to grid nodes, and compliance settings on buckets.

|11.0
|Added support for configuring platform services (CloudMirror replication, notifications, and Elasticsearch search integration) for buckets. Also added support for object tagging location constraints for buckets, and the Available consistency.

|10.4
|Added support for ILM scanning changes to versioning, Endpoint Domain Names page updates, conditions and variables in policies, policy examples, and the PutOverwriteObject permission.

|10.3
|Added support for versioning.

|10.2
|Added support for group and bucket access policies, and for multipart copy (UploadPartCopy).

|10.1
|Added support for multipart upload, virtual hosted-style requests, and v4 authentication.

|10.0
|Initial support of the S3 REST API by the StorageGRID system.The currently supported version of the _Simple Storage Service API Reference_ is 2006-03-01.

|===

// 2023 OCT 26, SGWS-27431
// 2023 OCT 5, SGWS-27457