---
permalink: s3/consistency-controls.html
sidebar: sidebar
keywords: consistency, consistency control, consistency values
summary: 'Consistency provides a balance between the availability of the objects and the consistency of those objects across different Storage Nodes and sites. You can change the consistency as required by your application.'
---
= Consistency values
:icons: font
:imagesdir: ../media/

[.lead]
Consistency provides a balance between the availability of the objects and the consistency of those objects across different Storage Nodes and sites. You can change the consistency as required by your application.

By default, StorageGRID guarantees read-after-write consistency for newly created objects. Any GET following a successfully completed PUT will be able to read the newly written data. Overwrites of existing objects, metadata updates, and deletes are eventually consistent. Overwrites generally take seconds or minutes to propagate, but can take up to 15 days.

If you want to perform object operations at a different consistency, you can:

* Specify a consistency for <<bucket-consistency-control,each bucket>>.
* Specify a consistency for <<api-operation-consistency-control,each API operation>>.
* Change the default grid-wide consistency by performing one of the following tasks:
** In the Grid Manager, go to *CONFIGURATION* > *System* > *Storage settings* > *Default consistency*.
** link:../admin/using-grid-management-api.html[Use the `grid-config` endpoint of the Grid Management private API].
+
NOTE: A change to the grid-wide consistency applies only to buckets created after the setting was changed. To determine the details of a change, see the audit log located at `/var/local/log` (search for *consistencyLevel*).

== Consistency values

The consistency affects how the metadata that StorageGRID uses to track objects is distributed between nodes, and therefore the availability of objects for client requests.

You can set the consistency for a bucket or an API operation to one of the following values:

* *All*: All nodes receive the data immediately, or the request will fail.
* *Strong-global*: Guarantees read-after-write consistency for all client requests across all sites.
* *Strong-site*: Guarantees read-after-write consistency for all client requests within a site.
* *Read-after-new-write*: (Default) Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Recommended for most cases.
* *Available*: Provides eventual consistency for both new objects and object updates. For S3 buckets, use only as required (for example, for a bucket that contains log values that are rarely read, or for HEAD or GET operations on keys that don't exist). Not supported for S3 FabricPool buckets.

== Use "Read-after-new-write" and "Available" consistency

When a HEAD or GET operation uses the "Read-after-new-write" consistency, StorageGRID performs the lookup in multiple steps, as follows:

* It first looks up the object using a low consistency.
* If that lookup fails, it repeats the lookup at the next consistency value until it reaches a consistency equivalent to the behavior for strong-global.

If a HEAD or GET operation uses the "Read-after-new-write" consistency but the object does not exist, the object lookup will always reach a consistency equivalent to the behavior for strong-global. Because this consistency requires multiple copies of the object metadata to be available at each site, you can receive a high number of 500 Internal Server errors if two or more Storage Nodes at the same site are unavailable.

Unless you require consistency guarantees similar to Amazon S3, you can prevent these errors for HEAD and GET operations by setting the consistency to "Available." When a HEAD or GET operation uses the "Available" consistency, StorageGRID provides eventual consistency only. It does not retry a failed operation at increasing consistency, so it does not require that multiple copies of the object metadata be available.

== [[api-operation-consistency-control]]Specify consistency for API operation

To set the consistency for an individual API operation,the consistency values must be supported for the operation, and you must specify the consistency in the request header. This example sets the consistency to "Strong-site" for a GetObject operation.

[subs="specialcharacters,quotes"]
----
GET /bucket/object HTTP/1.1
Date: date
Authorization: _authorization name_
Host: _host_
Consistency-Control: strong-site
----

NOTE: You must use the same consistency for both the PutObject and GetObject operations.

== [[bucket-consistency-control]]Specify consistency for bucket

To set the consistency for bucket, you can use the StorageGRID link:put-bucket-consistency-request.html[PUT Bucket consistency] request. Or you can link:../tenant/manage-bucket-consistency.html#change-bucket-consistency[change a bucket's consistency] from the Tenant Manager.

When setting the consistency for a bucket, be aware of the following:

* Setting the consistency for a bucket determines which consistency is used for S3 operations performed on the objects in the bucket or on the bucket configuration. It does not affect operations on the bucket itself.
* The consistency for an individual API operation overrides the consistency for the bucket.
* In general, buckets should use the default consistency, "Read-after-new-write." If requests aren't working correctly, change the application client behavior if possible. Or, configure the client to specify the consistency for each API request. Set the consistency at the bucket level only as a last resort.

== [[how-consistency-controls-and-ILM-rules-interact]]How consistency and ILM rules interact to affect data protection

Both your choice of consistency and your ILM rule affect how objects are protected. These settings can interact.

For example, the consistency used when an object is stored affects the initial placement of object metadata, while the ingest behavior selected for the ILM rule affects the initial placement of object copies. Because StorageGRID requires access to both an object's metadata and its data to fulfill client requests, selecting matching levels of protection for the consistency and ingest behavior can provide better initial data protection and more predictable system responses.

The following link:../ilm/data-protection-options-for-ingest.html[ingest options] are available for ILM rules:

Dual commit:: StorageGRID immediately makes interim copies of the object and returns success to the client. Copies specified in the ILM rule are made when possible.

Strict:: All copies specified in the ILM rule must be made before success is returned to the client.

Balanced:: StorageGRID attempts to make all copies specified in the ILM rule at ingest; if this is not possible, interim copies are made and success is returned to the client. The copies specified in the ILM rule are made when possible.

== Example of how the consistency and ILM rule can interact

include::../_include/consistency-and-ilm-rule-interaction.adoc[]