---
permalink: s3/upload-part.html
sidebar: sidebar
keywords: s3 UploadPart operation
summary: 'The UploadPart operation uploads a part in a multipart upload for an object.'
---
= UploadPart
:icons: font
:imagesdir: ../media/

[.lead]
The UploadPart operation uploads a part in a multipart upload for an object.

== Supported request headers

The following request headers are supported:

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`

== Request headers for server-side encryption

If you specified SSE-C encryption for the CreateMultipartUpload request, you must also include the following request headers in each UploadPart request:

* `x-amz-server-side-encryption-customer-algorithm`: Specify `AES256`.
* `x-amz-server-side-encryption-customer-key`: Specify the same encryption key that you provided in the CreateMultipartUpload request.
* `x-amz-server-side-encryption-customer-key-MD5`: Specify the same MD5 digest that you provided in the CreateMultipartUpload request.

CAUTION: The encryption keys you provide are never stored. If you lose an encryption key, you lose the corresponding object. Before using customer-provided keys to secure object data, review the considerations in link:using-server-side-encryption.html[Use server-side encryption].

If you specified a SHA-256 checksum during the CreateMultipartUpload request, you must also include the following request header in each UploadPart request:

* `x-amz-checksum-sha256`: Specify the SHA-256 checksum for this part.

== Unsupported request headers

The following request headers aren't supported:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`

== Versioning

Multipart upload consists of separate operations for initiating the upload, listing uploads, uploading parts, assembling the uploaded parts, and completing the upload. Objects are created (and versioned if applicable) when the CompleteMultipartUpload operation is performed.

// 2024 MAY 23, SGWS-31243