---
permalink: monitor/updating-snmp-agent.html
sidebar: sidebar
keywords: how to update the SNMP agent
summary: 'You can disable SNMP notifications, update community strings, or add or remove agent addresses, USM users, and trap destinations.'
---
= Update the SNMP agent
:icons: font
:imagesdir: ../media/

[.lead]
You can disable SNMP notifications, update community strings, or add or remove agent addresses, USM users, and trap destinations.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:../admin/admin-group-permissions.html[Root access permission].

.About this task
See link:configuring-snmp-agent.html[Configure the SNMP agent] for details about each field on the SNMP agent page. You must select *Save* at the bottom of the page to commit any changes you make on each tab.

.Steps
. Select *CONFIGURATION* > *Monitoring* > *SNMP agent*.
+
The SNMP agent page appears.

. To disable the SNMP agent on all grid nodes, clear the *Enable SNMP* checkbox, and select *Save*.
+
If you re-enable the SNMP agent, any previous SNMP configuration settings are retained.

. Optionally, update the information in the Basic configuration section:

.. As required, update the *System contact* and *System location*.

.. Optionally, select or clear the *Enable SNMP agent notifications* checkbox to control whether the StorageGRID SNMP agent sends trap and inform notifications.
+
When this checkbox is cleared, the SNMP agent supports read-only MIB access, but it doesn't send SNMP notifications.

.. Optionally, select or clear the *Enable authentication traps* checkbox to control whether the StorageGRID SNMP agent sends authentication traps when it receives improperly authenticated protocol messages.

. If you use SNMPv1 or SNMPv2c, optionally update or add a *Read-only community* in the Community strings section.

. To update trap destinations, select the Trap destinations tab in the Other configurations section.
+
Use this tab to define one or more destinations for StorageGRID trap or inform notifications. When you enable the SNMP agent and select *Save*, StorageGRID sends notifications to each defined destination when alerts are triggered. Standard notifications are also sent for the supported MIB-II entities (for example, ifDown and coldStart).
+
For details about what to enter, see link:../monitor/configuring-snmp-agent.html#create-trap-destinations[Create trap destinations].

* Optionally, update or remove the default trap community.
+
If you remove the default trap community, you must first ensure that any existing trap destinations use a custom community string.

 * To add a trap destination, select *Create*.
 * To edit a trap destination, select the radio button, and select *Edit*.
 * To remove a trap destination, select the radio button, and select *Remove*.
 * To commit your changes, select *Save* at the bottom of the page.

. To update agent addresses, select the Agent addresses tab in the Other configurations section.
+
Use this tab to specify one or more "listening addresses." These are the StorageGRID addresses on which the SNMP agent can receive queries.
+
For details about what to enter, see link:../monitor/configuring-snmp-agent.html#create-agent-addresses[Create agent addresses].

 * To add an agent address, select *Create*.
 * To edit an agent address, select the radio button, and select *Edit*. 
 * To remove an agent address, select the radio button, and select *Remove*. 
 * To commit your changes, select *Save* at the bottom of the page.

. To update USM users, select the USM users tab in the Other configurations section.
+
Use this tab to define the USM users who are authorized to query the MIB or to receive traps and informs.
+
For details about what to enter, see link:../monitor/configuring-snmp-agent.html#create-usm-users[Create USM users].

 * To add a USM user, select *Create*. 
 * To edit a USM user, select the radio button, and select *Edit*. 
+
The username for an existing USM user can't be changed. If you need to change a username, you must remove the user and create a new one.
+
NOTE: If you add or remove a user's authoritative engine ID and that user is currently selected for a destination, you must edit or remove the destination. Otherwise, a validation error occurs when you save the SNMP agent configuration.

* To remove a USM user, select the radio button, and select *Remove*. 
+
NOTE: If the user you removed is currently selected for a trap destination, you must edit or remove the destination. Otherwise, a validation error occurs when you save the SNMP agent configuration.

* To commit your changes, select *Save* at the bottom of the page.

. When you have updated the SNMP agent configuration, select *Save*.
