---
permalink: maintain/decommissioning-multiple-storage-nodes.html
sidebar: sidebar
keywords: storagegrid, decommission nodes, storage node, multiple storage nodes
summary: 'If you need to remove more than one Storage Node, you can decommission them either sequentially or in parallel.'
---
= Decommission multiple Storage Nodes
:icons: font
:imagesdir: ../media/

[.lead]
If you need to remove more than one Storage Node, you can decommission them either sequentially or in parallel.

CAUTION: Use caution when you decommission Storage Nodes in a grid containing software-based metadata-only nodes. If you decommission all nodes configured to store _both_ objects and metadata, the ability to store objects is removed from the grid. See link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes] for more information about metadata-only Storage Nodes.

* If you decommission Storage Nodes sequentially, you must wait for the first Storage Node to complete decommissioning before starting to decommission the next Storage Node.
* If you decommission Storage Nodes in parallel, the Storage Nodes simultaneously process decommission tasks for all Storage Nodes being decommissioned. This can result in a situation where all permanent copies of a file are marked as "read‐only," temporarily disabling deletion in grids where this functionality is enabled.
