---
permalink: maintain/grid-node-decommissioning.html
sidebar: sidebar
keywords: storagegrid, decommission, remove grid node
summary: 'You can use the node decommission procedure to remove one or more grid nodes at one or more sites. You cannot decommission the primary Admin Node.'
---
= Grid node decommission
:icons: font
:imagesdir: ../media/

[.lead]
You can use the node decommission procedure to remove one or more grid nodes at one or more sites. You can't decommission the primary Admin Node.

== When to decommission a node

Use the node decommission procedure when any of the following are true:

* You added a larger Storage Node in an expansion and you want to remove one or more smaller Storage Nodes, while at the same time preserving objects.
+
TIP: If you want to replace an older appliance with a newer appliance, consider https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html[cloning the appliance node^] instead of adding a new appliance in an expansion and then decommissioning the old appliance. 

* You require less total storage.
* You no longer require a Gateway Node.
* You no longer require a non-primary Admin Node.
* Your grid includes a disconnected node that you can't recover or bring back online.
* Your grid includes an Archive Node.

== How to decommission a node

You can decommission connected grid nodes or disconnected grid nodes. 

Decommission connected nodes::
In general, you should decommission grid nodes only when they are connected to the StorageGRID system and only when all nodes are in normal health (have green icons on the *NODES* pages and on the *Decommission Nodes* page). 
+
For instructions, see link:decommissioning-connected-grid-nodes.html[Decommission connected grid nodes].

Decommission disconnected nodes:: 
In some cases, you might need to decommission a grid node that is not currently connected to the grid (one whose Health is Unknown or Administratively Down).
+
For instructions, see link:decommissioning-disconnected-grid-nodes.html[Decommission disconnected grid nodes].

== What to consider before decommissioning a node

Before performing either procedure, review the considerations for each type of node:

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html[Considerations for Admin or Gateway Node decommission]

* link:considerations-for-decommissioning-storage-nodes.html[Considerations for Storage Node decommission]

