---
permalink: maintain/recovering-from-non-primary-admin-node-failures.html
sidebar: sidebar
keywords: storagegrid, recover, non-primary admin node failure
summary: 'You must complete the following tasks to recover from a non-primary Admin Node failure. One Admin Node hosts the Configuration Management Node \(CMN\) service and is known as the primary Admin Node. Although you can have multiple Admin Nodes, each StorageGRID system includes only one primary Admin Node. All other Admin Nodes are non-primary Admin Nodes.'
---
= Recover from non-primary Admin Node failures
:icons: font
:imagesdir: ../media/

[.lead]
You must complete the following tasks to recover from a non-primary Admin Node failure. One Admin Node hosts the Configuration Management Node (CMN) service and is known as the primary Admin Node. Although you can have multiple Admin Nodes, each StorageGRID system includes only one primary Admin Node. All other Admin Nodes are non-primary Admin Nodes.

Follow these high-level steps to recover a non-primary Admin Node:
 
. link:copying-audit-logs-from-failed-non-primary-admin-node.html[Copy audit logs from the failed non-primary Admin Node]
. link:replacing-non-primary-admin-node.html[Replace the non-primary Admin Node]
. link:selecting-start-recovery-to-configure-non-primary-admin-node.html[Select Start Recovery to configure the non-primary Admin Node]
. link:restoring-audit-log-on-recovered-non-primary-admin-node.html[Restore the audit log on a recovered non-primary Admin Node]
. link:restoring-admin-node-database-non-primary-admin-node.html[Restore the Admin Node database when recovering a non-primary Admin Node]
. link:restoring-prometheus-metrics-non-primary-admin-node.html[Restore Prometheus metrics when recovering a non-primary Admin Node]