---
permalink: maintain/understanding-adc-service-quorum.html
sidebar: sidebar
keywords: storagegrid, recover, adc, adc quorum
summary: 'You might not be able to decommission certain Storage Nodes at a site if too few Administrative Domain Controller \(ADC\) services would remain after the decommissioning.'
---
= What is the ADC quorum?
:icons: font
:imagesdir: ../media/

[.lead]
You might not be able to decommission certain Storage Nodes at a site if too few Administrative Domain Controller (ADC) services would remain after the decommissioning.

The ADC service, which is found on some Storage Nodes, maintains grid topology information and provides configuration services to the grid. The StorageGRID system requires a quorum of ADC services to be available at each site and at all times.

You can't decommission a Storage Node if removing the node would cause the ADC quorum to no longer be met. To satisfy the ADC quorum during a decommissioning, a minimum of three Storage Nodes at each site must have the ADC service. If a site has more than three Storage Nodes with the ADC service, a simple majority of those nodes must remain available after the decommissioning: `((0.5 * _Storage Nodes with ADC_) + 1)`

CAUTION: Use caution when you decommission Storage Nodes in a grid containing software-based metadata-only nodes. If you decommission all nodes configured to store _both_ objects and metadata, the ability to store objects is removed from the grid. See link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes] for more information about metadata-only Storage Nodes.

For example, suppose a site currently includes six Storage Nodes with ADC services and you want to decommission three Storage Nodes. Because of the ADC quorum requirement, you must complete two decommission procedures, as follows:

* In the first decommission procedure, you must ensure that four Storage Nodes with ADC services remain available: `((0.5 * 6) + 1)`. This means that you can only decommission two Storage Nodes initially.
* In the second decommission procedure, you can remove the third Storage Node because the ADC quorum now only requires three ADC services to remain available: `((0.5 * 4) + 1)`.

If you need to decommission a Storage Node but are unable to because of the ADC quorum requirement, add a new Storage Node in an link:../expand/index.html[expansion] and specify that it should have an ADC service. Then, decommission the existing Storage Node.


