---
permalink: primer/what-admin-node-is.html
sidebar: sidebar
keywords: admin nodes
summary: 'Admin Nodes provide management services such as system configuration, monitoring, and logging. Admin Nodes can also be used to load balance S3 client traffic. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.'
---
= What is an Admin Node?
:icons: font
:imagesdir: ../media/

[.lead]
Admin Nodes provide management services such as system configuration, monitoring, and logging. Admin Nodes can also be used to load balance S3 client traffic. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.

== Differences between primary and non-primary Admin Nodes

When you sign in to the Grid Manager or the Tenant Manager, you are connecting to an Admin Node. You can connect to any Admin Node, and each Admin Node displays a similar view of the StorageGRID system. However, the primary Admin Node provides more functionality than non-primary Admin Nodes. For example, most maintenance procedures must be performed from the primary Admin Nodes.

The table summarizes the capabilities of primary and non-primary Admin Nodes.

[cols="2a,1a,1a" options="header"]
|===

| Capabilities
| Primary Admin Node
| Non-primary Admin Node

| Includes the <<ams,AMS>> service
| Yes
| Yes

| Includes the <<cmn,CMN>> service
| Yes
| No

| Includes the <<nms,NMS>> service
| Yes
| Yes

| Includes the <<prometheus,Prometheus>> service
| Yes
| Yes

| Includes the <<ssm,SSM>> service
| Yes
| Yes

| Includes the <<load-balancer,Load Balancer>> and <<high-availability,High Availability>> services
| Yes
| Yes

| Supports the <<mgmt-api,Management Application Program Interface>> (mgmt-api)
| Yes
| Yes

| Can be used for all network-related maintenance tasks, for example IP address change and updating NTP servers
| Yes
| No

| Can perform EC rebalance after Storage Node expansion
| Yes
| No

| Can be used for the volume restoration procedure
| Yes
| Yes

| Can collect log files and system data from one or more nodes
| Yes
| No

| Sends alert notifications, AutoSupport packages, and SNMP traps and informs
| Yes. Acts as the <<preferred-sender,preferred sender>>.
| Yes. Acts as a standby sender.
|===



== [[preferred-sender]]Preferred sender Admin Node

If your StorageGRID deployment includes multiple Admin Nodes, the primary Admin Node is the preferred sender for alert notifications, AutoSupport packages, and SNMP traps and informs. 

Under normal system operations, only the preferred sender sends notifications. However, all other Admin Nodes monitor the preferred sender. If a problem is detected, other Admin Nodes act as _standby senders_.

Multiple notifications might sent in these cases:

* If Admin Nodes become "islanded" from each other, both the preferred sender and the standby senders will attempt to send notifications, and multiple copies of notifications might be received.

* If standby sender detects problems with the preferred sender and starts sending notifications, the preferred sender might regain its ability to send notifications. If this occurs, duplicate notifications might be sent. The standby sender will stop sending notifications when it no longer detects errors on the preferred sender.
+
NOTE: When you test AutoSupport packages, all Admin Nodes send the test. When you test alert notifications, you must sign in to every Admin Node to verify connectivity.

== Primary services for Admin Nodes

The following table shows the primary services for Admin Nodes; however, this table does not list all node services.

[cols="1a,2a" options="header"]
|===
| Service| Key function

| [[ams]]Audit Management System (AMS)
| Tracks system activity and events.

| [[cmn]]Configuration Management Node (CMN)
| Manages system-wide configuration.

| [[high-availability]]High Availability
| Manages high availability virtual IP addresses for groups of Admin Nodes and Gateway Nodes.

*Note:* This service is also found on Gateway Nodes.


| [[load-balancer]]Load Balancer
| Provides load balancing of S3 traffic from clients to Storage Nodes.

*Note:* This service is also found on Gateway Nodes.

| [[mgmt-api]]Management Application Program Interface (mgmt-api)
| Processes requests from the Grid Management API and the Tenant Management API. 

| [[nms]]Network Management System (NMS)
| Provides functionality for the Grid Manager.

| [[prometheus]]Prometheus
| Collects and stores time-series metrics from the services on all nodes.

| [[ssm]]Server Status Monitor (SSM)
| Monitors the operating system and underlying hardware.
|===







