---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html
sidebar: sidebar
keywords: grid node, add node, add site, expand, expansion
summary: 'Follow this procedure to add grid nodes to existing sites or to add a new site. You can only perform one type of expansion at a time.'
---
= Add grid nodes to existing site or add new site
:icons: font
:imagesdir: ../media/

[.lead]
Follow this procedure to add grid nodes to existing sites or to add a new site. You can only perform one type of expansion at a time.

.Before you begin

* You have the link:../admin/admin-group-permissions.html[Root access or Maintenance permission].
* All existing nodes in the grid are up and running across all sites.
* Any previous expansion, upgrade, decommissioning, or recovery procedures are complete.
+
NOTE: You are prevented from starting an expansion while another expansion, upgrade, recovery, or active decommission procedure is in progress. However, if necessary, you can pause a decommission procedure to start an expansion.

.Steps

. link:updating-subnets-for-grid-network.html[Update subnets for Grid Network].
. link:deploying-new-grid-nodes.html[Deploy new grid nodes].
. link:performing-expansion.html[Perform expansion].
