---
permalink: ilm/requirements-for-s3-object-lock.html
sidebar: sidebar
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy
summary: 'You must review the requirements for enabling the global S3 Object Lock setting, the requirements for creating compliant ILM rules and ILM policies, and the restrictions StorageGRID places on buckets and objects that use S3 Object Lock.'
---
= Requirements for S3 Object Lock
:icons: font
:imagesdir: ../media/

[.lead]
You must review the requirements for enabling the global S3 Object Lock setting, the requirements for creating compliant ILM rules and ILM policies, and the restrictions StorageGRID places on buckets and objects that use S3 Object Lock.

== Requirements for using the global S3 Object Lock setting

* You must enable the global S3 Object Lock setting using the Grid Manager or the Grid Management API before any S3 tenant can create a bucket with S3 Object Lock enabled.
* Enabling the global S3 Object Lock setting allows all S3 tenant accounts to create buckets with S3 Object Lock enabled.
* After you enable the global S3 Object Lock setting, you can't disable the setting.
* You can't enable the global S3 Object Lock unless the default rule in all active ILM policies is _compliant_ (that is, the default rule must comply with the requirements of buckets with S3 Object Lock enabled).
* When the global S3 Object Lock setting is enabled, you can't create a new ILM policy or activate an existing ILM policy unless the default rule in the policy is compliant. After the global S3 Object Lock setting has been enabled, the ILM rules and ILM policies pages indicate which ILM rules are compliant.

== Requirements for compliant ILM rules

If you want to enable the global S3 Object Lock setting, you must ensure that the default rule in all active ILM policies is compliant. A compliant rule satisfies the requirements of both buckets with S3 Object Lock enabled and any existing buckets that have legacy Compliance enabled:

* It must create at least two replicated object copies or one erasure-coded copy.
* These copies must exist on Storage Nodes for the entire duration of each line in the placement instructions.
* Object copies can't be saved in a Cloud Storage Pool.
* At least one line of the placement instructions must start at day 0, using *Ingest time* as the reference time.
* At least one line of the placement instructions must be "forever."

== Requirements for ILM policies

When the global S3 Object Lock setting is enabled, active and inactive ILM policies can include both compliant and non-compliant rules.

* The default rule in an active or inactive ILM policy must be compliant.
* Non-compliant rules only apply to objects in buckets that don't have S3 Object Lock enabled or that don't have the legacy Compliance feature enabled.
* Compliant rules can apply to objects in any bucket; S3 Object Lock or legacy Compliance does not need to be enabled for the bucket.

link:example-7-compliant-ilm-policy-for-s3-object-lock.html[Example of a compliant ILM policy for S3 Object Lock]

include::../_include/s3-object-lock-requirements.adoc[]

.Related information

* link:../tenant/creating-s3-bucket.html[Create an S3 bucket]
* link:../tenant/update-default-retention-settings.html[Update  S3 Object Lock default retention]
* link:../s3/use-s3-api-for-s3-object-lock.html[Use S3 REST API to configure S3 Object Lock]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html[Example 7: Compliant ILM policy for S3 Object Lock]