---
permalink: ilm/what-storage-pool-is.html
sidebar: sidebar
keywords: what is a storage pool
summary: 'A storage pool is a logical grouping of Storage Nodes.'
---
= What is a storage pool?
:icons: font
:imagesdir: ../media/

[.lead]
A storage pool is a logical grouping of Storage Nodes.

When you install StorageGRID, one storage pool per site is automatically created. You can configure additional storage pools as needed for your storage requirements.

NOTE: Storage Nodes can be configured during installation to contain object data and object metadata, or only object metadata. Metadata-only Storage Nodes can't be used in storage pools. For more information, see link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes].

Storage pools have two attributes:

* *Storage grade*: For Storage Nodes, the relative performance of backing storage.
* *Site*: The data center where objects will be stored.

Storage pools are used in ILM rules to determine where object data is stored and the type of storage used. When you configure ILM rules for replication, you select one or more storage pools.